# Análisis y depuración de bases administrativas: Giros y BDUA

Este notebook documenta el proceso de limpieza, transformación y análisis exploratorio
de las bases administrativas del sistema de salud colombiano: Giros (ADRES).

El objetivo es construir una base analítica consistente que permita su uso posterior
en análisis estadístico y modelos predictivos.

### **Librerias**

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import unicodedata
import re
import os

# Ver qué ubicación datos en Kaggle
print(os.listdir('/kaggle/input/datasets/geraldinelaverde/inicial-giros'))

['Recursos_del_Sistema_General_Giros_20251018.csv']

### **IMPORTACIONES**

In [2]:

# Leer datos iniciales
ruta_archivo = '/kaggle/input/datasets/geraldinelaverde/inicial-giros/Recursos_del_Sistema_General_Giros_20251018.csv'

df_Giros_inicial = pd.read_csv(ruta_archivo, low_memory=False)

df_Giros_inicial.head()

,Fecha de pago,Identificacion- NIT,Nombre Razon Social,Descripcion,Fuente,Valor Girado,Concepto Pago,Ordenes de Pago
0,2015-01-29,800136069,MUNICIPIO DE FORTUL,SISTEMA GENERAL DE PARTICIPACIONES SALUD PUBLI...,Nación,27.047.767,GIRO SGP SALUD PUBLICA VIG 2014,9207515
1,2015-01-29,890000464,MUNICIPIO DE ARMENIA,SISTEMA GENERAL DE PARTICIPACIONES SALUD PUBLI...,Nación,130.243.583,GIRO SGP SALUD PUBLICA VIG 2014,9207615
2,2015-01-29,899999372,MUNICIPIO DE SIBATE,SISTEMA GENERAL DE PARTICIPACIONES SALUD PUBLI...,Nación,12.600.367,GIRO SGP SALUD PUBLICA VIG 2014,9207715
3,2015-01-29,890980112,MUNICIPIO DE BELLO,SISTEMA GENERAL DE PARTICIPACIONES SALUD PUBLI...,Nación,214.941.350,GIRO SGP SALUD PUBLICA VIG 2014,9207815
4,2015-01-29,890985285,MUNICIPIO DE VEGACHI,SISTEMA GENERAL DE PARTICIPACIONES SALUD PUBLI...,Nación,9.040.907,GIRO SGP SALUD PUBLICA VIG 2014,9207915

### **ANÁLISIS EXPLORATORIO**

In [3]:
# =============================================================================
# ANÁLISIS EXPLORATORIO DE DATOS (EDA) - df_Giros_incial
# =============================================================================

print("Dimensiones del dataset:", df_Giros_inicial.shape)
display(df_Giros_inicial.head())

print("\nTipos de datos:")
display(df_Giros_inicial.dtypes)

print("\nValores nulos por columna:")
display(df_Giros_inicial.isnull().sum().sort_values(ascending=False))

print("\nColumnas con tipos mezclados")
for col in df_Giros_inicial.columns:
    tipos = df_Giros_inicial[col].map(type).nunique()
    if tipos > 1:
        print(f"{col} tiene {tipos} tipos de datos")

Dimensiones del dataset: (50065, 8)

,Fecha de pago,Identificacion- NIT,Nombre Razon Social,Descripcion,Fuente,Valor Girado,Concepto Pago,Ordenes de Pago
0,2015-01-29,800136069,MUNICIPIO DE FORTUL,SISTEMA GENERAL DE PARTICIPACIONES SALUD PUBLI...,Nación,27.047.767,GIRO SGP SALUD PUBLICA VIG 2014,9207515
1,2015-01-29,890000464,MUNICIPIO DE ARMENIA,SISTEMA GENERAL DE PARTICIPACIONES SALUD PUBLI...,Nación,130.243.583,GIRO SGP SALUD PUBLICA VIG 2014,9207615
2,2015-01-29,899999372,MUNICIPIO DE SIBATE,SISTEMA GENERAL DE PARTICIPACIONES SALUD PUBLI...,Nación,12.600.367,GIRO SGP SALUD PUBLICA VIG 2014,9207715
3,2015-01-29,890980112,MUNICIPIO DE BELLO,SISTEMA GENERAL DE PARTICIPACIONES SALUD PUBLI...,Nación,214.941.350,GIRO SGP SALUD PUBLICA VIG 2014,9207815
4,2015-01-29,890985285,MUNICIPIO DE VEGACHI,SISTEMA GENERAL DE PARTICIPACIONES SALUD PUBLI...,Nación,9.040.907,GIRO SGP SALUD PUBLICA VIG 2014,9207915

Tipos de datos:

Fecha de pago          object
Identificacion- NIT     int64
Nombre Razon Social    object
Descripcion            object
Fuente                 object
Valor Girado           object
Concepto Pago          object
Ordenes de Pago        object
dtype: object

Valores nulos por columna:

Fecha de pago          0
Identificacion- NIT    0
Nombre Razon Social    0
Descripcion            0
Fuente                 0
Valor Girado           0
Concepto Pago          0
Ordenes de Pago        0
dtype: int64

Columnas con tipos mezclados